### ISSUE TITLE
Update css-tree version to newest

### ISSUE THREAD

**Issue by aventic** [svg/svgo#1004]
Are you able to update the version of css-tree to the latest version? We're having some issues on macOS where the create.js file would load in as an error saying:

```
Module build failed: <PATH_TO_PROJECT>/node_modules/css-tree/lib/syntax/create.js:1
(function (exports, require, module, __filename, __dirname) { �
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<PATH_TO_PROJECT>/node_modules/css-tree/lib/syntax/index.js:14:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

And the optimization of files would simply crash and not run.

Thanks in regards.

**Comment by GreLI** [comment]
No, last time I tried to bump it, it failed with some error, so I stuck to the latest working version. Couldn't quickly resolve it, I guess it's some issue with CSS Tree internals.

**Comment by aventic** [comment]
@GreLI - alright, and you have not encountered any errors on mac computer?

**Comment by TrySound** [comment]
We will try with @lahmatiy
