### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by oytunistrator** [svg/svgo#1032]
```
events.js:167
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'path' of undefined
    at optimizeOnceCallback (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/svgo/lib/svgo.js:48:29)
    at /Users/oytun/Projects/Mopas/bahceevler.com/node_modules/svgo/lib/svgo.js:70:9
    at SAXParser.sax.onend (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/svgo/lib/svgo/svg2js.js:169:13)
    at emit (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/sax/lib/sax.js:624:35)
    at end (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.write (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/sax/lib/sax.js:975:14)
    at SAXParser.close (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/svgo/lib/svgo/svg2js.js:182:28)
    at SVGO._optimizeOnce (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/svgo/lib/svgo.js:62:5)
    at optimizeOnceCallback (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/svgo/lib/svgo.js:43:26)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:182:13)
    at Immediate.<anonymous> (/Users/oytun/Projects/Mopas/bahceevler.com/node_modules/through2-concurrent/through2-concurrent.js:37:14)
    at runCallback (timers.js:694:11)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

###

**Comment by GreLI** [comment]
Duplicates #1031
