### ISSUE TITLE
convertStyleToAttrs false results in TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by joepagan** [svg/svgo#1043]
I have found an issue where trying to run the following svg through svgo I get the following errors when compiling with Webpack only when the plugin `convertStyleToAttrs` is `false`.

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 242 242">
  <defs>
    <style>
      .cls-1 {
        fill: url(#New_Gradient_Swatch);
      }

      .cls-2 {
        fill: url(#New_Gradient_Swatch-2);
      }

      .cls-3 {
        fill: url(#New_Gradient_Swatch-3);
      }

      .cls-4 {
        fill: #32bad9;
      }
    </style>
    <linearGradient id="New_Gradient_Swatch" x1="124" y1="38.91" x2="229.15" y2="38.91" gradientUnits="userSpaceOnUse">
      <stop offset="0.01" stop-color="#293c61" />
      <stop offset="1" stop-color="#32bad9" />
    </linearGradient>
    <linearGradient id="New_Gradient_Swatch-2" y1="203.09" x2="229.15" y2="203.09" xlink:href="#New_Gradient_Swatch" />
    <linearGradient id="New_Gradient_Swatch-3" x1="2.56" y1="121" x2="49.96" y2="121" xlink:href="#New_Gradient_Swatch" />
  </defs>
  <g id="Layer_2" data-name="Layer 2">
    <path class="cls-1" d="M198,78.25l31.11-18A121.38,121.38,0,0,0,124-.44V35.49A85.49,85.49,0,0,1,198,78.25Z" />
    <path class="cls-2" d="M124,206.51v35.93a121.38,121.38,0,0,0,105.15-60.73l-31.11-18A85.49,85.49,0,0,1,124,206.51Z" />
    <path class="cls-3" d="M38.49,121A85.07,85.07,0,0,1,50,78.25l-31.11-18a121.27,121.27,0,0,0,0,121.42l31.11-18A85.07,85.07,0,0,1,38.49,121Z" />
  </g>
  <g id="Layer_4" data-name="Layer 4">
    <path class="cls-4" d="M99.85,194.48a77,77,0,0,1-38.92-27.83L34.76,186A109.86,109.86,0,0,0,158,225L147.69,194.1A77.05,77.05,0,0,1,99.85,194.48Z" />
    <path class="cls-4" d="M135.05,44.88l4.82-32.18A110,110,0,0,0,25.18,72.33L54.29,86.86A77.43,77.43,0,0,1,135.05,44.88Z" />
    <path class="cls-4" d="M200.9,125.83a77.05,77.05,0,0,1-17.28,44.63L208.85,191a109.44,109.44,0,0,0,24.55-63.39h0l-32.5-1.79Z" />
    <path class="cls-4" d="M200.9,125.82l32.5,1.79A109.47,109.47,0,0,0,216,61.91L188.62,79.56A77,77,0,0,1,200.9,125.82Z" />
    <path class="cls-4" d="M163.26,19,151.51,49.33a77.53,77.53,0,0,1,37.11,30.23L216,61.91A110.21,110.21,0,0,0,163.26,19Z" />
    <path class="cls-4" d="M52.34,152.06,22.57,165.21a110.2,110.2,0,0,0,45.31,50.67l16.36-28.13A77.6,77.6,0,0,1,52.34,152.06Z" />
  </g>
</svg>
```

The error:

```bash
｢wdm｣: TypeError: Cannot read property '0' of undefined
    at getPropertyDescriptor (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/utils/names.js:65:24)
    at getPropertyFingerprint (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/restructure/6-restructBlock.js:68:20)
    at List.<anonymous> (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/restructure/6-restructBlock.js:213:27)
    at List.eachRight (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/utils/list.js:182:12)
    at Object.processRule (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/restructure/6-restructBlock.js:211:18)
    at Object.enter (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/restructure/6-restructBlock.js:293:25)
    at Object.<anonymous> (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/walker/create.js:13:16)
    at List.walkNode (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/walker/create.js:161:19)
    at List.eachRight (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/utils/list.js:182:12)
    at Object.eval [as StyleSheet] (eval at createTypeIterator (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/walker/create.js:112:12), <anonymous>:5:15)
    at walkNode (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/walker/create.js:158:37)
    at walk (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/node_modules/css-tree/lib/walker/create.js:214:9)
    at restructBlock (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/restructure/6-restructBlock.js:270:5)
    at module.exports (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/restructure/index.js:27:5)
    at compressChunk (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/compress.js:77:9)
    at compress (/Users/joe/var/www/project/node_modules/svgo/node_modules/csso/lib/compress.js:153:9)
```

When convertStyleToAttrs is true, it compiles fine.
When I comment out the CSS using the `fill: url(#id)` css it also compiles fine.

Here is a full list of the other plugins I am using:
```javascript
plugins: [
        { removeDoctype: true },
        { removeXMLProcInst: true },
        { removeComments: true },
        { removeMetadata: true },
        { removeUselessDefs: true },
        { removeTitle: true },
        { removeDesc: true },
        { convertColors: { shorthex: false } },
        { convertPathData: true },
        { convertStyleToAttrs: false },
        { minifyStyles: true },
        { removeUselessStrokeAndFill: false },
        { prefixIds: { active: true } },
        { mergePaths: false },
    ],
```

Similar error on this issue but no `;;` anywhere in my files:
https://github.com/svg/svgo/issues/352

Edit*: I added the wrong plugin before (thanks to some caching it appear to be the other one), the one that appears to be the problem is `convertStyleToAttrs `

**Comment by strarsis** [comment]
@joepagan: I can't reproduce this issue with svgo from master:
````
$ git clone https://github.com/svg/svgo
$ cd svgo
$ npm install
$ npm build
$ ./bin/svgo --disable={convertStyleToAttrs} -i test.svg -o test.min.svg

test.svg:
Done in 61 ms!
2.135 KiB - 19% = 1.729 KiB

````

**Comment by joepagan** [comment]
Works for myself using your test procedure, must have been the webpack plugin, thank you for investigating & sorry for wasting your time @strarsis
