### ISSUE TITLE
Error in parsing SVG: No whitespace between attributes on very simple SVG

### ISSUE THREAD

**Issue by kylemh** [svg/svgo#1136]
**The Error:**
```
src/index.js → dist/index.development.cjs.js, dist/index.development.esm.js...
[!] (plugin react-svg) Error: Could not load /Code/svg-icons/src/svgs/alert.svg (imported by /Code/svg-icons/src/index.js): Error in parsing SVG: No whitespace between attributes
Line: 0
Column: 89
Char: M
Error: Could not load /Code/svg-icons/src/svgs/alert.svg (imported by /Code/svg-icons/src/index.js): Error in parsing SVG: No whitespace between attributes
Line: 0
Column: 89
Char: M
    at error (/Code/svg-icons/node_modules/rollup/dist/rollup.js:9408:30)
    at Promise.resolve.then.catch.err (/Code/svg-icons/node_modules/rollup/dist/rollup.js:15818:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**The SVG in question:**
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 0C9.813 0 7.8.533 5.96 1.6A11.793 11.793 0 0 0 1.6 5.96C.533 7.8 0 9.813 0 12s.533 4.2 1.6 6.04a11.793 11.793 0 0 0 4.36 4.36C7.8 23.467 9.813 24 12 24s4.2-.533 6.04-1.6a11.793 11.793 0 0 0 4.36-4.36C23.467 16.2 24 14.187 24 12s-.533-4.2-1.6-6.04a11.793 11.793 0 0 0-4.36-4.36C16.2.533 14.187 0 12 0zm0 17.36a1.31 1.31 0 0 1-.96-.4c-.267-.267-.4-.6-.4-1s.133-.733.4-1 .587-.4.96-.4.693.133.96.4.4.6.4 1-.133.733-.4 1a1.31 1.31 0 0 1-.96.4zm1.44-4.72h-2.8V6h2.8v6.64z"/></svg>
```

**The Rollup Config**
```javascript
import { terser } from 'rollup-plugin-terser';
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';
import resolve from 'rollup-plugin-node-resolve';
import sourceMaps from 'rollup-plugin-sourcemaps';
import replace from 'rollup-plugin-replace';
import reactSvg from 'rollup-plugin-react-svg';
import { insertIf } from '@innocuous/functions';
import svgoConfig from './svgo.config';

const extensions = ['.js', '.jsx'];

// Inspiration for rollup config stems mostly from https://github.com/palmerhq/tsdx
const generateOutputConfig = ({ format, environment }) => ({
  file: `dist/index.${environment}.${format}.js`,
  format,

  // Do not let Rollup call Object.freeze() on namespace import objects
  // (i.e. import * as namespaceImportObject from...) that are accessed dynamically.
  freeze: false,

  // Do not let Rollup add a `__esModule: true` property when generating exports for non-ESM formats.
  esModule: false,

  treeshake: {
    // We assume reading a property of an object never has side-effects.
    // getters and setters on objects WILL be removed.
    //
    // @example
    // const foo = {
    //  get bar() {
    //    console.log('effect');
    //    return 'bar';
    //  }
    // }
    //
    // const result = foo.bar;
    // const illegalAccess = foo.quux.tooDeep;
    //
    // Soooooo... Don't use getters and setters 🙏
    propertyReadSideEffects: false,
  },
  name: '@nike/icons',
  sourcemap: true,
  globals: { react: 'React', 'react-native': 'ReactNative' },
  exports: 'named',
});

export default {
  input: 'src/index.js',
  output: [
    generateOutputConfig({ format: 'cjs', environment: process.env.BUILD }),
    generateOutputConfig({ format: 'esm', environment: process.env.BUILD }),
  ],
  plugins: [
    resolve({
      extensions,
      mainFields: ['module', 'main', 'browser'],
    }),
    json(),
    babel(),
    reactSvg({ svgo: svgoConfig }),
    replace({
      'process.env.NODE_ENV': process.env.BUILD,
    }),
    sourceMaps(),
    ...insertIf(
      process.env.BUILD === 'production',
      terser({
        // https://github.com/terser-js/terser#minify-options
        sourcemap: true,
        output: { comments: false },
        compress: {
          pure_getters: true,
          passes: 10,
        },
        warnings: true,
      }),
    ),
  ],
  external: ['react'],
};
```

**The SVGO Config**
```javascript
// https://github.com/svg/svgo#what-it-can-do
export default {
  plugins: [
    { cleanupIDs: true, params: { minify: true } },
    { cleanupListOfValues: true },
    { convertColors: true },
    { convertStyleToAttrs: true },
    { convertTransform: true },
    { mergePaths: true },
    { minifyStyles: true },
    { moveElemesAttrsToGroup: true },
    {
      removeAttrs: true,
      params: { /* exceptions */ attrs: 'fill-rule' },
    },
    { removeComments: true },
    { removeDesc: true, params: { removeAny: true } },
    { removeDimensions: true },
    { removeDoctype: true },
    { removeEditorsNSData: true },
    { removeEmptyAttrs: true },
    { removeEmptyContainers: true },
    { removeEmptyText: true },
    { removeNonInheritableGroupAttrs: true },
    { removeTitle: false },
    { removeUnknownsAndDefaults: true },
    { removeUnusedNS: true },
    { removeUselessDefs: true },
    { removeUselessStrokeAndFill: true },
    { removeXMLProcInst: true },
    { sortAttrs: true },
    {
      addAttributesToSVGElement: {
        attribute: 'fill="currentColor',
      }
    }
  ],
  floatPrecision: 3,
  multipass: true,
};
```

**Comment by kylemh** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 0C9.813 0 7.8.533 5.96 1.6A11.793 11.793 0 0 0 1.6 5.96C.533 7.8 0 9.813 0 12s.533 4.2 1.6 6.04a11.793 11.793 0 0 0 4.36 4.36C7.8 23.467 9.813 24 12 24s4.2-.533 6.04-1.6a11.793 11.793 0 0 0 4.36-4.36C23.467 16.2 24 14.187 24 12s-.533-4.2-1.6-6.04a11.793 11.793 0 0 0-4.36-4.36C16.2.533 14.187 0 12 0zm0 17.36a1.31 1.31 0 0 1-.96-.4c-.267-.267-.4-.6-.4-1s.133-.733.4-1 .587-.4.96-.4.693.133.96.4.4.6.4 1-.133.733-.4 1a1.31 1.31 0 0 1-.96.4zm1.44-4.72h-2.8V6h2.8v6.64z"/></svg>

It was because I was _missing_ whitespace between the end `"` and `/` in `path`.

**Comment by kylemh** [comment]
Nevermind. For some reason sometimes the above SVG can get parsed, but then the next file fails.

**Comment by kylemh** [comment]
Found it!

```
{
  addAttributesToSVGElement: {
    attribute: 'fill="currentColor',
  }
}
```

Forgot the trailing `"`! 😝

**Comment by LOLISK** [comment]
In wich file do you find the svgo config ?

**Comment by kylemh** [comment]
You don't need one, but if you define one you can put it whever you want.

**Comment by dubpirate** [comment]
I had the same error, I fixed it by removing all tags and attributes that were not present in the example svg you mentioned:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 0C9.813 0 7.8.533 5.96 1.6A11.793 11.793 0 0 0 1.6 5.96C.533 7.8 0 9.813 0 12s.533 4.2 1.6 6.04a11.793 11.793 0 0 0 4.36 4.36C7.8 23.467 9.813 24 12 24s4.2-.533 6.04-1.6a11.793 11.793 0 0 0 4.36-4.36C23.467 16.2 24 14.187 24 12s-.533-4.2-1.6-6.04a11.793 11.793 0 0 0-4.36-4.36C16.2.533 14.187 0 12 0zm0 17.36a1.31 1.31 0 0 1-.96-.4c-.267-.267-.4-.6-.4-1s.133-.733.4-1 .587-.4.96-.4.693.133.96.4.4.6.4 1-.133.733-.4 1a1.31 1.31 0 0 1-.96.4zm1.44-4.72h-2.8V6h2.8v6.64z"/></svg>
```

As well as adding the trailing space from the original solution.

Thanks heaps!
