### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by avieseegobinsc** [svg/svgo#1170]
Hi,
I'm getting an error when I try to optimize an SVG and I'm not sure what to do with the error that's returned. The SVG I'm trying to optimize renders as expected so I don't think the SVG is malformed or broken in any way.

This error occurs on the command line, Sublime Text ([link](https://packagecontrol.io/packages/SVGO)) and with the npm package ([link](https://www.npmjs.com/package/svgo)) in my JS code.

CLI
---
```
> svgo broken.svg
TypeError: Cannot read property 'data' of undefined
```

Sublime
---
Error occurred when trying to prettify the svg:
```
Error: (node:10287) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/plugins/_transforms.js:36:33
    at Array.forEach (<anonymous>)
    at exports.transform2js (/Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/plugins/_transforms.js:22:46)
    at convertTransform (/Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/plugins/convertTransform.js:77:16)
    at Object.exports.fn (/Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/plugins/convertTransform.js:52:13)
    at /Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/lib/svgo/plugins.js:61:45
    at Array.filter (<anonymous>)
    at monkeys (/Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/lib/svgo/plugins.js:48:39)
    at /Users/george-bones/Library/Application Support/Sublime Text 3/Packages/SVGO/node_modules/svgo/lib/svgo/plugins.js:68:17
    at Array.filter (<anonymous>)
(node:10287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
npm package
---
Error occurred when trying to run a `.optimize` on an SVG string:
```
TypeError: Cannot read property 'data' of undefined
    at /var/bs/sites/george_api/node_modules/svgo/plugins/_transforms.js:36:32
    at Array.forEach (native)
    at exports.transform2js (/var/bs/sites/george_api/node_modules/svgo/plugins/_transforms.js:22:46)
    at convertTransform (/var/bs/sites/george_api/node_modules/svgo/plugins/convertTransform.js:77:16)
    at Object.exports.fn (/var/bs/sites/george_api/node_modules/svgo/plugins/convertTransform.js:52:13)
    at /var/bs/sites/george_api/node_modules/svgo/lib/svgo/plugins.js:61:45
    at Array.filter (native)
    at monkeys (/var/bs/sites/george_api/node_modules/svgo/lib/svgo/plugins.js:48:39)
    at /var/bs/sites/george_api/node_modules/svgo/lib/svgo/plugins.js:68:17
    at Array.filter (native)
```

Any help on this would be greatly appreciated. I can also send you the SVG file if required.

**Comment by avieseegobinsc** [comment]
I ended up figuring out what was the issue. In my SVG I had a syntax error in one of my attributes:
```
transform="(0,-80)"
```
I'm not sure if a syntax error like this can be called out with SVGO but that would be helpful

**Comment by TrySound** [comment]
Hi! Could you please show us broken svg?
