### ISSUE TITLE
Plugin reusePaths implicitly depends on removeXMLProcInst being enabled

### ISSUE THREAD

**Issue by mrackwitz** [svg/svgo#1205]
As the title states, the plugin reusePaths implicitly depends on removeXMLProcInst being enabled. I think this should be at least documented – better fixed.

If a document has an XML processing instruction and the plugin `removeXMLProcInst` is disabled, then said element is preceding the root element, which the implementation of the reusePaths does not properly handle. This causes the following crash:
```
TypeError: Cannot read property 'splice' of undefined
    at module.exports.JSAPI.spliceContent (<#REDACTED#>/node_modules/svgo/lib/svgo/jsAPI.js:135:25)
    at Object.exports.fn (<#REDACTED#>/node_modules/svgo/plugins/reusePaths.js:126:19)
    at <#REDACTED#>/node_modules/svgo/lib/svgo/plugins.js:95:27
    at Array.forEach (<anonymous>)
    at full (<#REDACTED#>/node_modules/svgo/lib/svgo/plugins.js:93:13)
    at <#REDACTED#>/node_modules/svgo/lib/svgo/plugins.js:25:24
    at Array.forEach (<anonymous>)
    at module.exports (<#REDACTED#>/node_modules/svgo/lib/svgo/plugins.js:15:13)
    at <#REDACTED#>/node_modules/svgo/lib/svgo.js:70:17
    at SAXParser.sax.onend (<#REDACTED#>/node_modules/svgo/lib/svgo/svg2js.js:169:13)
```

The problem is here: https://github.com/svg/svgo/blob/07ca9764f71fb946adc23f4ea9f19070d335305d/plugins/reusePaths.js#L124-L126

**Comment by strarsis** [comment]
PR for replacing sax with saxes: https://github.com/svg/svgo/pull/1281

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/pull/1551. Will be released soon.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.6.0
