### ISSUE TITLE
Running svgo on Azure PaaS

### ISSUE THREAD

**Issue by markgibbons25** [svg/svgo#1236]
Hello, I am trying to run SVGO 1.3.2 on Azure WebApps, invoked via .NET. I have run an npm install locally, then copied everything up to the instance, along with Node.exe 12. 
The code that invokes node.exe is here https://github.com/kamsar/Dianoga/blob/5ce6bf5b9df45272477de245a31840d6a76f7911/src/Dianoga/Optimizers/CommandLineToolOptimizer.cs#L104 

Parameters: `bin\svgo\ --input=\"{tempFilePath}\" --output=\"{tempOutputPath}\" --disable=removeUselessDefs --disable=cleanupIDs`

This works flawlessly when run locally, however on the WebApp it works for some svg's, but for others I see errors like this:

	7244 22:37:53 ERROR Dianoga: Unable to optimize /Themes//images/icons/ico-search-white due to a processing error! It will be unchanged.
	Exception: System.InvalidOperationException
	Message: "D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node.exe "D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\bin\svgo" --input="D:\local\Temp\tmp7FC.tmp" --output="D:\local\Temp\tmp7FD.tmp" --disable=removeUselessDefs --disable=cleanupIDs" exited with unexpected exit code 1. Output: 
	}
	  ]
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\bin\\svgo'
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\lib\\svgo\\coa.js',
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\node_modules\\util.promisify\\index.js',
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\node_modules\\util.promisify\\implementation.js',
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\node_modules\\object.getownpropertydescriptors\\index.js',
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\node_modules\\object.getownpropertydescriptors\\implementation.js',
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\node_modules\\es-abstract\\2019\\CreateDataProperty.js',
		'D:\\home\\site\\wwwroot\\App_Data\\Dianoga Tools\\SVGO\\node_modules\\svgo\\node_modules\\es-abstract\\GetIntrinsic.js',
	  requireStack: [
	  code: 'MODULE_NOT_FOUND',
		at Module.require (internal/modules/cjs/loader.js:848:19) {
		at Function.Module._load (internal/modules/cjs/loader.js:723:14)
		at Module.load (internal/modules/cjs/loader.js:811:32)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
		at Module._compile (internal/modules/cjs/loader.js:955:30)
		at Object.<anonymous> (D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\es-abstract\GetIntrinsic.js:165:12)
		at require (internal/modules/cjs/helpers.js:74:18)
		at Module.require (internal/modules/cjs/loader.js:848:19)
		at Function.Module._load (internal/modules/cjs/loader.js:686:27)
		at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\bin\svgo
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\lib\svgo\coa.js
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\util.promisify\index.js
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\util.promisify\implementation.js
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\object.getownpropertydescriptors\index.js
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\object.getownpropertydescriptors\implementation.js
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\es-abstract\2019\CreateDataProperty.js
	- D:\home\site\wwwroot\App_Data\Dianoga Tools\SVGO\node_modules\svgo\node_modules\es-abstract\GetIntrinsic.js
	Require stack:
	Error: Cannot find module 'function-bind'

		^
		throw err;
	internal/modules/cjs/loader.js:796

	Source: Dianoga
	   at Dianoga.Optimizers.CommandLineToolOptimizer.ExecuteProcess(String arguments)
	   at Dianoga.Optimizers.CommandLineToolOptimizer.ProcessOptimizer(OptimizerArgs args)
	   at Dianoga.Optimizers.OptimizerProcessor.Process(OptimizerArgs args)
	   at (Object , Object )
	   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
	   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
	   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
	   at Dianoga.Processors.Pipelines.DianogaOptimize.ExtensionBasedOptimizer.ProcessOptimize(ProcessorArgs args)
	   at (Object , Object )
	   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
	   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
	   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
	   at Dianoga.MediaOptimizer.Process(MediaStream stream, MediaOptions options)

Any ideas would be appreciated.

**Comment by markgibbons25** [comment]
Changed to use https://github.com/twardoch/svgop which has resolved the issue.
