### ISSUE TITLE
Test failure with css-select 2.1.0

### ISSUE THREAD

**Issue by musicinmybrain** [svg/svgo#1315]
From a clean checkout of master,

```
npm update && npm test
```

results in:

```
  1 failing

  1) plugins tests
       inlineStyles.15:
     Error: Unmatched selector: / [layout][vertical][reverse]
      at parse (node_modules/css-what/lib/parse.js:61:15)
      at compileUnsafe (node_modules/css-select/lib/compile.js:32:17)
      at addAdapter (node_modules/css-select/index.js:14:16)
      at select (node_modules/css-select/index.js:27:21)
      at CSSselect (node_modules/css-select/index.js:76:12)
      at module.exports.JSAPI.querySelectorAll (lib/svgo/jsAPI.js:344:21)
      at Object.exports.fn (plugins/inlineStyles.js:110:36)
      at /home/ben/src/svgo/lib/svgo/plugins.js:95:27
      at Array.forEach (<anonymous>)
      at full (lib/svgo/plugins.js:93:13)
      at /home/ben/src/svgo/lib/svgo/plugins.js:25:24
      at Array.forEach (<anonymous>)
      at module.exports (lib/svgo/plugins.js:15:13)
      at /home/ben/src/svgo/lib/svgo.js:70:17
      at SAXParser.sax.onend (lib/svgo/svg2js.js:169:13)
      at emit (node_modules/sax/lib/sax.js:624:35)
      at end (node_modules/sax/lib/sax.js:667:5)
      at SAXParser.write (node_modules/sax/lib/sax.js:975:14)
      at SAXParser.close (node_modules/sax/lib/sax.js:157:38)
      at module.exports (lib/svgo/svg2js.js:182:28)
      at SVGO._optimizeOnce (lib/svgo.js:64:5)
      at /home/ben/src/svgo/lib/svgo.js:57:14
      at new Promise (<anonymous>)
      at SVGO.optimize (lib/svgo.js:26:12)
      at /home/ben/src/svgo/test/plugins/_index.js:47:33



npm ERR! Test failed.  See above for more details.
```

but, again from a clean checkout, applying:

```patch
diff --git a/package.json b/package.json
index 4f4f182..f11215b 100644
--- a/package.json
+++ b/package.json
@@ -50,7 +50,7 @@
   "dependencies": {
     "chalk": "^2.4.1",
     "coa": "^2.0.2",
-    "css-select": "^2.0.0",
+    "css-select": "~2.0.0",
     "css-select-base-adapter": "^0.1.1",
     "css-tree": "1.0.0-alpha.37",
     "csso": "^4.0.2",
```

followed by:

```
npm update && npm test
```

gives:

```
  353 passing (3s)
```

**Comment by TrySound** [comment]
Fixed in v2
