### ISSUE TITLE
Error when minimize big svg 

### ISSUE THREAD

**Issue by MarcoCivettini** [svg/svgo#1411]
**Describe the bug**
Hi,
I've try to minimize a big svg (65MB) 
but after a lot of time the svgo was not compressed and return me this error.

Someone can help me?

`RangeError: Maximum call stack size exceeded
    at JSAPI.spliceContent (C:\temp\prova\node_modules\svgo\lib\svgo\jsAPI.js:13
0:30)
    at C:\temp\prova\node_modules\svgo\plugins\collapseGroups.js:81:26
    at Array.forEach (<anonymous>)
    at Object.exports.fn (C:\temp\prova\node_modules\svgo\plugins\collapseGroups
.js:45:22)
    at C:\temp\prova\node_modules\svgo\lib\svgo\plugins.js:65:37
    at Array.filter (<anonymous>)
    at monkeys (C:\temp\prova\node_modules\svgo\lib\svgo\plugins.js:53:35)
    at perItem (C:\temp\prova\node_modules\svgo\lib\svgo\plugins.js:81:10)
    at module.exports (C:\temp\prova\node_modules\svgo\lib\svgo\plugins.js:32:16
)
    at optimize (C:\temp\prova\node_modules\svgo\lib\svgo.js:58:13)
`

**Screenshots**
![Immagine 2021-03-09 080140](https://user-images.githubusercontent.com/15126452/110431160-b5a32e80-80ad-11eb-8b23-757c3b418d78.png)

**Desktop (please complete the following information):**
 - SVGO Version [2.2.1]
 - NodeJs Version [e.g 14.15.1]
 - OS: [Windows 10]
 
**Additional context**
If i try with a smaller image like 15MB the procedure run correctly without any error message

**Comment by TrySound** [comment]
Hi! SVGO is not designed to process so big images. Though you can try to extend memory limit in node
```
NODE_OPTIONS="--max_old_space_size=4096" svgo ...
```

This will work for linux or mac os. Not sure how to set environment variable in windows.

**Comment by XhmikosR** [comment]
See https://github.com/svg/svgo/issues/954#issuecomment-782624823
