### ISSUE TITLE
HTML comment in CSS comment breaks css-tools

### ISSUE THREAD

**Issue by McSodbrenner** [svg/svgo#1515]
**Describe the bug**
An HTML comment in a CSS comment breaks css-tools with the exception:
```
TypeError: Cannot read property '0' of undefined
  | at compareSpecificity (/var/www/html/.../node_modules/svgo/lib/css-tools.js:131:21)
  | at stable.inplace (/var/www/html/.../node_modules/svgo/lib/style.js:164:5)
  | at pass (/var/www/html/.../node_modules/stable/stable.js:85:15)
  | at exec (/var/www/html/.../node_modules/stable/stable.js:49:7)
  | at Function.stable.inplace (/var/www/html/.../node_modules/stable/stable.js:18:18)
  | at computeStyle (/var/www/html/.../node_modules/svgo/lib/style.js:163:10)
  | at Object.enter (/var/www/html/.../node_modules/svgo/plugins/removeHiddenElems.js:57:31)
  | at visit (/var/www/html/.../node_modules/svgo/lib/xast.js:58:15)
  | at visit (/var/www/html/.../node_modules/svgo/lib/xast.js:64:7)
  | at module.exports (/var/www/html/.../node_modules/svgo/lib/svgo/plugins.js:43:13)
  | on line 4, offset 2
```

**To Reproduce**
Input file:
```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100" height="100">
	<title>Test</title>
	<style>
		/*
		* <!-- Comment -->
		*/
		.foo { opacity: 1; }
		.bar { opacity: 1; }
	</style>
</svg>
```

**Expected behavior**
The HTML comment should not break svgo.

**Desktop (please complete the following information):**
 - SVGO Version 2.3.1
 - NodeJs Version 14.17.3
 - OS: Windows 10

**Comment by SethFalco** [comment]
Sorry it took so long to get around to your issue! Finally tackling the backlog now.

I've been unable to reproduce this behavior, though. I've tried using the same SVGO and Node.js version as you. Can you still reproduce this issue, and if so, could you share the config/SVG?
