### ISSUE TITLE
"Unbound namespace prefix" & wiped files

### ISSUE THREAD

**Issue by nwwt** [svg/svgo#1530]
**Describe the bug**
Trying to run svgo on SVG originally based on [KanjiVG](http://kanjivg.tagaini.net/) such as the one contained [in this archive](https://github.com/svg/svgo/files/7017191/03005.zip) causes it to bug out with `Error: Error in parsing SVG: Unbound namespace prefix: "kvg"` and, if called on a folder, to wipe other opened SVG files in the progress (as in: they become 0 byte files).

Output:
```
Error: Error in parsing SVG: Unbound namespace prefix: "kvg"
Line: 49
Column: 34
Char: >
File: 03005.svg
    at processSVGData (/usr/lib/node_modules/svgo/lib/svgo/coa.js:367:11)
    at /usr/lib/node_modules/svgo/lib/svgo/coa.js:344:7
    at async Promise.all (index 0)
    at async Command.action (/usr/lib/node_modules/svgo/lib/svgo/coa.js:237:7)
    at async Promise.all (index 0)
```

**To Reproduce**
1. `svgo 03005.svg`

**Expected behavior**
svgo does its magic.

**Desktop (please complete the following information):**
 - SVGO 2.4.0, 2.5.0
 - NodeJs 16.7.0. 16.8.0
 - OS: Arch

**Comment by TrySound** [comment]
Looks like kvg namespace is defined in unusual way not supported by sax parser we use.

**Comment by pritulaziah** [comment]
Hello! Maybe [my solution](https://github.com/pritulaziah/kanji-react-icons/blob/master/scripts/parser.ts) will help someone

**Comment by Lonli-Lokli** [comment]
I also have this error with this svg
`<svg viewBox="0 0 16 16">
    <path id="wifi3" d="M8,0C5.2,0,2.4,0.8,0,2.2l1.3,2.3c4.1-2.4,9.2-2.4,13.3,0L16,2.2C13.6,0.7,10.8,0,8,0z" />
    <path id="wifi2" d="M2.7,6.8L4,9.2c2.5-1.5,5.5-1.5,8,0l1.3-2.4C11.7,5.9,9.9,5.4,8,5.4C6.1,5.4,4.3,5.9,2.7,6.8z" />
    <path id="wifi1" d="M5.4,11.5L8.1,16l2.6-4.6c-0.8-0.5-1.7-0.7-2.6-0.7C7.2,10.7,6.2,11,5.4,11.5z" />
    <animate xlink:href="#wifi1" attributeName="fill-opacity" dur="1.2s" values="0.5;1;1;1;0.5"
        repeatCount="indefinite" />
    <animate xlink:href="#wifi2" attributeName="fill-opacity" dur="1.2s" values="0.5;0.5;1;1;0.5"
        repeatCount="indefinite" />
    <animate xlink:href="#wifi3" attributeName="fill-opacity" dur="1.2s" values="0.5;0.5;0.5;1;0.5"
        repeatCount="indefinite" />
</svg>`

**Comment by GreLI** [comment]
@Lonli-Lokli yep, this is not a proper XML, `xlink` namespace is not defined. Should be something like `<svg xmlns:xlink="http://www.w3.org/1999/xlink"`
