### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1581]
**Describe the bug**
If I run `svgo -i in.svg -o out.svg`

I get:
```bash
TypeError: Cannot read property 'includes' of undefined
    at Object.enter (/usr/local/lib/node_modules/svgo/plugins/removeAttrs.js:96:23)
    at visit (/usr/local/lib/node_modules/svgo/lib/xast.js:68:30)
    at visit (/usr/local/lib/node_modules/svgo/lib/xast.js:77:7)
    at invokePlugins (/usr/local/lib/node_modules/svgo/lib/svgo/plugins.js:38:11)
    at optimize (/usr/local/lib/node_modules/svgo/lib/svgo.js:55:13)
    at optimize (/usr/local/lib/node_modules/svgo/lib/svgo-node.js:63:10)
    at processSVGData (/usr/local/lib/node_modules/svgo/lib/svgo/coa.js:385:18)
    at /usr/local/lib/node_modules/svgo/lib/svgo/coa.js:368:7
    at async Promise.all (index 0)
    at async Command.action (/usr/local/lib/node_modules/svgo/lib/svgo/coa.js:261:7)
```

**Screenshots**

![Screenshot from 2021-09-20 20-13-35](https://user-images.githubusercontent.com/15687581/134053090-5c3057d7-b633-493e-8c81-07596cba48da.png)

**Desktop (please complete the following information):**
 - `svgo -version` `2.6.1`
 - `node --version` `v14.17.6`
 - OS: `hostnamectl`
 ```bash
  Static hostname: lws84.imws.tuwien.ac.at
       Icon name: computer-laptop
         Chassis: laptop
      Machine ID: 96434f58f7644401a3f9d69da903899d
         Boot ID: e593a5286c674b19aa220912c1265dec
Operating System: Fedora 34 (Workstation Edition) 
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.13.16-200.fc34.x86_64
    Architecture: x86-64
 Hardware Vendor: Lenovo
  Hardware Model: ThinkPad P15 Gen 1
```

**Comment by TrySound** [comment]
How does your config look like?

**Comment by JoKalliauer** [comment]
> How does your config look like?

[svgo.config.js.txt](https://github.com/svg/svgo/files/7201562/svgo.config.js.txt)

However I think it is a installation-problem, since the problem also occurs in an empty folder

```bash
mkdir emptyFolder
cd emptyFolder
wget -q https://commons.wikimedia.org/wiki/Special:FilePath/Test.svg -O in.svg
svgo -i in.svg -o out.svg
```
leads to
```bash
TypeError: Cannot read property 'includes' of undefined
    at Object.enter (/usr/local/lib/node_modules/svgo/plugins/removeAttrs.js:96:23)
    at visit (/usr/local/lib/node_modules/svgo/lib/xast.js:68:30)
    at visit (/usr/local/lib/node_modules/svgo/lib/xast.js:77:7)
    at invokePlugins (/usr/local/lib/node_modules/svgo/lib/svgo/plugins.js:38:11)
    at optimize (/usr/local/lib/node_modules/svgo/lib/svgo.js:55:13)
    at optimize (/usr/local/lib/node_modules/svgo/lib/svgo-node.js:63:10)
    at processSVGData (/usr/local/lib/node_modules/svgo/lib/svgo/coa.js:385:18)
    at /usr/local/lib/node_modules/svgo/lib/svgo/coa.js:368:7
    at async Promise.all (index 0)
    at async Command.action (/usr/local/lib/node_modules/svgo/lib/svgo/coa.js:261:7)
```
![Screenshot from 2021-09-21 10-21-15](https://user-images.githubusercontent.com/15687581/134137076-8a55e3f7-d9bc-4807-9211-eff0eef806e2.png)

**Comment by TrySound** [comment]
Looks like invalid usage. removeAttrs is customization plugin. And btw will be removed in v3.
There is validation fix btw https://github.com/svg/svgo/pull/1582
