### ISSUE TITLE
'Cannot read properties of undefined' error in reflectPoint

### ISSUE THREAD

**Issue by vltansky** [svg/svgo#2018]
**Describe the bug**

**To Reproduce**
Running this SVG via `convertPathData` plugin fails in `reflectPoint` function cause  `qControlPoint` is undefined
svg:
```
<svg viewBox="0 0 404.7699 220.5982" width="5000px" height="2724.9828476646435px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none">
            <defs></defs>
            <style>.a6izo4zJpcolor {fill:#CC8561;fill-opacity:1;}.aBuJNUX_TZcolors-0 {fill:#CC8561;fill-opacity:1;}.aD6z1nYkhcolor {fill:#CC8561;fill-opacity:1;}.aepP6SCxH2colors-0 {fill:#CC8561;fill-opacity:1;}.aQjBTis6fwcolors-0 {fill:#CC8561;fill-opacity:1;}</style>
            <g opacity="1" transform="rotate(0 134.53279999999998 91.1866)">
                <svg width="143.8938" height="26.8625" x="134.53279999999998" y="91.1866" version="1.1" preserveAspectRatio="none" viewBox="2.64 -29.2 158.56 29.599999999999998">
                <g transform="matrix(1 0 0 1 0 0)" class="a6izo4zJpcolor"><path d="M21.88 0L17.20 0L10.52-9.64L7.04-6.36L7.04 0L2.64 0L2.64-29.20L7.04-29.20L7.04-10.68L16.64-20.88L21.44-20.88L13.32-12.12L21.88 0Z M32.96 0L28.56 0L28.56-20.92L32.96-20.92L32.96 0ZM32.96-24.36L28.56-24.36L28.56-29.20L32.96-29.20L32.96-24.36Z M52.96-4.56L53.88-1.08Q53.04-0.68 51.56-0.18Q50.08 0.32 48.40 0.32L48.40 0.32Q47.36 0.32 46.44 0.04Q45.52-0.24 44.82-0.80Q44.12-1.36 43.72-2.26Q43.32-3.16 43.32-4.44L43.32-4.44L43.32-17.52L40.56-17.52L40.56-20.92L43.32-20.92L43.32-27.80L47.72-27.80L47.72-20.92L52.28-20.92L52.28-17.52L47.72-17.52L47.72-5.84Q47.80-4.72 48.42-4.22Q49.04-3.72 49.96-3.72L49.96-3.72Q50.88-3.72 51.72-4.04Q52.56-4.36 52.96-4.56L52.96-4.56Z M59.04-10.48L59.04-10.48Q59.04-12.68 59.80-14.64Q60.56-16.60 61.98-18.08Q63.40-19.56 65.40-20.42Q67.40-21.28 69.88-21.28L69.88-21.28Q73.12-21.28 75.46-19.86Q77.80-18.44 78.96-16.08L78.96-16.08L74.68-14.72Q73.92-16.04 72.64-16.78Q71.36-17.52 69.80-17.52L69.80-17.52Q68.48-17.52 67.34-17Q66.20-16.48 65.36-15.54Q64.52-14.60 64.04-13.32Q63.56-12.04 63.56-10.48L63.56-10.48Q63.56-8.96 64.06-7.66Q64.56-6.36 65.42-5.40Q66.28-4.44 67.42-3.90Q68.56-3.36 69.84-3.36L69.84-3.36Q70.64-3.36 71.44-3.58Q72.24-3.80 72.90-4.20Q73.56-4.60 74.06-5.12Q74.56-5.64 74.80-6.24L74.80-6.24L79.12-4.96Q78.08-2.60 75.64-1.10Q73.20 0.40 69.88 0.40L69.88 0.40Q67.44 0.40 65.44-0.48Q63.44-1.36 62.02-2.86Q60.60-4.36 59.82-6.32Q59.04-8.28 59.04-10.48Z M105.52-12.76L105.52 0L101.12 0L101.12-11.72Q101.12-14.60 100.10-15.98Q99.08-17.36 97.16-17.36L97.16-17.36Q96.24-17.36 95.32-17Q94.40-16.64 93.58-15.98Q92.76-15.32 92.12-14.42Q91.48-13.52 91.16-12.44L91.16-12.44L91.16 0L86.76 0L86.76-29.20L91.16-29.20L91.16-16.72Q92.36-18.88 94.42-20.08Q96.48-21.28 98.92-21.28L98.92-21.28Q100.88-21.28 102.14-20.58Q103.40-19.88 104.16-18.72Q104.92-17.56 105.22-16.02Q105.52-14.48 105.52-12.76L105.52-12.76Z M124.12 0.40L124.12 0.40Q121.68 0.40 119.68-0.46Q117.68-1.32 116.26-2.80Q114.84-4.28 114.06-6.24Q113.28-8.20 113.28-10.40L113.28-10.40Q113.28-12.60 114.06-14.58Q114.84-16.56 116.26-18.06Q117.68-19.56 119.68-20.42Q121.68-21.28 124.16-21.28L124.16-21.28Q126.60-21.28 128.58-20.40Q130.56-19.52 131.96-18.06Q133.36-16.60 134.10-14.66Q134.84-12.72 134.84-10.60L134.84-10.60Q134.84-10.12 134.80-9.70Q134.76-9.28 134.72-9L134.72-9L117.96-9Q118.08-7.60 118.62-6.48Q119.16-5.36 120.02-4.54Q120.88-3.72 121.98-3.28Q123.08-2.84 124.28-2.84L124.28-2.84Q125.16-2.84 126.02-3.06Q126.88-3.28 127.60-3.70Q128.32-4.12 128.88-4.72Q129.44-5.32 129.76-6.04L129.76-6.04L133.52-4.96Q132.44-2.60 129.94-1.10Q127.44 0.40 124.12 0.40ZM117.84-12.04L130.48-12.04Q130.36-13.36 129.82-14.48Q129.28-15.60 128.44-16.38Q127.60-17.16 126.48-17.60Q125.36-18.04 124.12-18.04L124.12-18.04Q122.88-18.04 121.78-17.60Q120.68-17.16 119.84-16.38Q119-15.60 118.48-14.48Q117.96-13.36 117.84-12.04L117.84-12.04Z M161.20-12.76L161.20 0L156.80 0L156.80-11.72Q156.80-14.68 155.86-16.02Q154.92-17.36 153.08-17.36L153.08-17.36Q152.12-17.36 151.16-17Q150.20-16.64 149.36-15.98Q148.52-15.32 147.86-14.42Q147.20-13.52 146.84-12.44L146.84-12.44L146.84 0L142.44 0L142.44-20.92L146.44-20.92L146.44-16.72Q147.64-18.84 149.92-20.06Q152.20-21.28 154.96-21.28L154.96-21.28Q156.84-21.28 158.04-20.60Q159.24-19.92 159.94-18.74Q160.64-17.56 160.92-16.02Q161.20-14.48 161.20-12.76L161.20-12.76Z"></path></g>
                </svg>
            </g>
            <g opacity="1" transform="rotate(0 82.84639999999999 0)">
                <svg width="247.2665" height="71.5241" x="82.84639999999999" y="0" version="1.1" preserveAspectRatio="none" viewBox="0.92 -29 101.9156 29.48">
                <g transform="matrix(1 0 0 1 0 0)" class="aD6z1nYkhcolor"><path d="M12.88-2.76L12.96-2.80Q13.12-2.80 13.22-2.64Q13.32-2.48 13.20-2.40L13.20-2.40Q11.72-0.92 10.32-0.22Q8.92 0.48 7.36 0.48L7.36 0.48Q5.60 0.48 4.36-0.36Q3.12-1.20 3.12-3.20L3.12-3.20L3.12-12.08Q3.12-13.32 2.68-13.80Q2.24-14.28 1.08-14.28L1.08-14.28Q1.04-14.28 0.98-14.40Q0.92-14.52 0.92-14.64L0.92-14.64Q0.92-14.80 0.96-14.90Q1-15 1.08-15L1.08-15Q3.12-15.08 4.38-15.88Q5.64-16.68 6.32-18.32L6.32-18.32Q6.40-18.48 6.66-18.48Q6.92-18.48 6.92-18.32L6.92-18.32L6.92-15.12Q9.24-15.16 12.12-15.48L12.12-15.48Q12.20-15.48 12.30-15.18Q12.40-14.88 12.40-14.52L12.40-14.52Q12.40-14.12 12.26-13.74Q12.12-13.36 11.96-13.40L11.96-13.40Q9.36-13.96 6.92-14L6.92-14L6.92-4.52Q6.92-3 7.70-2.28Q8.48-1.56 9.76-1.56L9.76-1.56Q11.36-1.56 12.88-2.76L12.88-2.76Z M35.08-0.48Q35.24-0.48 35.24-0.24Q35.24 0 35.08 0L35.08 0Q34.04 0 33.40-0.04L33.40-0.04L31.08-0.08L28.68-0.04Q28.08 0 27.04 0L27.04 0Q26.96 0 26.96-0.24Q26.96-0.48 27.04-0.48L27.04-0.48Q28.28-0.48 28.74-1.06Q29.20-1.64 29.20-3.24L29.20-3.24L29.20-9Q29.20-11.16 28.40-12.20Q27.60-13.24 25.92-13.24L25.92-13.24Q24.96-13.24 23.94-12.84Q22.92-12.44 22.16-11.76L22.16-11.76L22.16-3.24Q22.16-1.64 22.62-1.06Q23.08-0.48 24.32-0.48L24.32-0.48Q24.48-0.48 24.48-0.24Q24.48 0 24.32 0L24.32 0Q23.28 0 22.64-0.04L22.64-0.04L20.32-0.08L17.92-0.04Q17.32 0 16.28 0L16.28 0Q16.20 0 16.20-0.24Q16.20-0.48 16.28-0.48L16.28-0.48Q17.52-0.48 17.98-1.06Q18.44-1.64 18.44-3.24L18.44-3.24L18.44-23.56Q18.44-24.96 18.18-25.56Q17.92-26.16 17.28-26.16L17.28-26.16Q16.72-26.16 15.76-25.72L15.76-25.72L15.72-25.72Q15.60-25.72 15.50-25.94Q15.40-26.16 15.48-26.20L15.48-26.20L21.32-28.96L21.52-29Q21.72-29 21.94-28.82Q22.16-28.64 22.16-28.48L22.16-28.48L22.16-12.64Q25-15.92 28.24-15.92L28.24-15.92Q30.40-15.92 31.66-14.54Q32.92-13.16 32.92-10.92L32.92-10.92L32.92-3.24Q32.92-1.64 33.38-1.06Q33.84-0.48 35.08-0.48L35.08-0.48Z M49.76-15.84Q50.68-15.84 51.54-15.18Q52.40-14.52 52.40-13.60L52.40-13.60Q52.40-12.76 51.88-12.22Q51.36-11.68 50.52-11.68L50.52-11.68Q49.92-11.68 49.54-11.92Q49.16-12.16 48.76-12.64L48.76-12.64Q48.40-13.04 48.14-13.22Q47.88-13.40 47.52-13.40L47.52-13.40Q47.12-13.40 46.66-13.10Q46.20-12.80 45.24-11.84L45.24-11.84L45.24-3.24Q45.24-1.64 46-1.06Q46.76-0.48 48.80-0.48L48.80-0.48Q48.96-0.48 48.96-0.24Q48.96 0 48.80 0L48.80 0Q47.40 0 46.60-0.04L46.60-0.04L43.36-0.08L41-0.04Q40.40 0 39.36 0L39.36 0Q39.24 0 39.24-0.24Q39.24-0.48 39.36-0.48L39.36-0.48Q40.60-0.48 41.04-1.06Q41.48-1.64 41.48-3.24L41.48-3.24L41.48-10.76Q41.48-12 41.18-12.58Q40.88-13.16 40.24-13.16L40.24-13.16Q39.56-13.16 38.32-12.60L38.32-12.60L38.24-12.60Q38.12-12.60 38.06-12.80Q38-13 38.08-13.04L38.08-13.04L43.64-15.76Q43.88-15.84 43.92-15.84L43.92-15.84Q44.36-15.84 44.74-15.02Q45.12-14.20 45.20-12.80L45.20-12.80Q46.84-14.48 47.90-15.16Q48.96-15.84 49.76-15.84L49.76-15.84Z M60.36-19.80Q59.20-19.80 58.56-20.44Q57.92-21.08 57.92-22.24L57.92-22.24Q57.92-23.28 58.58-23.90Q59.24-24.52 60.36-24.52L60.36-24.52Q61.48-24.52 62.08-23.92Q62.68-23.32 62.68-22.24L62.68-22.24Q62.68-21.08 62.08-20.44Q61.48-19.80 60.36-19.80L60.36-19.80ZM56.52 0Q56.40 0 56.40-0.24Q56.40-0.48 56.52-0.48L56.52-0.48Q57.76-0.48 58.20-1.06Q58.64-1.64 58.64-3.24L58.64-3.24L58.64-10.40Q58.64-11.76 58.36-12.36Q58.08-12.96 57.44-12.96L57.44-12.96Q56.92-12.96 55.96-12.52L55.96-12.52L55.92-12.52Q55.76-12.52 55.68-12.74Q55.60-12.96 55.72-13L55.72-13L61.76-15.80L61.88-15.84Q62.08-15.84 62.28-15.64Q62.48-15.44 62.48-15.28L62.48-15.28L62.48-14.40Q62.40-12.80 62.40-10.48L62.40-10.48L62.40-3.24Q62.40-1.64 62.86-1.06Q63.32-0.48 64.56-0.48L64.56-0.48Q64.68-0.48 64.68-0.24Q64.68 0 64.56 0L64.56 0Q63.52 0 62.92-0.04L62.92-0.04L60.52-0.08L58.16-0.04Q57.56 0 56.52 0L56.52 0Z M85.64-15.44Q85.72-15.44 85.72-15.20Q85.72-14.96 85.64-14.96L85.64-14.96Q84.48-14.96 83.58-14.08Q82.68-13.20 81.88-11.36L81.88-11.36L76.96 0Q76.92 0.20 76.52 0.20L76.52 0.20Q76.20 0.20 76.08 0L76.08 0L69.96-12.12Q69.12-13.88 68.48-14.42Q67.84-14.96 66.92-14.96L66.92-14.96Q66.80-14.96 66.80-15.20Q66.80-15.44 66.92-15.44L66.92-15.44Q67.64-15.44 68.12-15.40L68.12-15.40L70.80-15.36L73.88-15.40Q74.56-15.44 75.76-15.44L75.76-15.44Q75.88-15.44 75.88-15.20Q75.88-14.96 75.76-14.96L75.76-14.96Q73.44-14.96 73.44-14.04L73.44-14.04Q73.44-13.80 73.64-13.40L73.64-13.40L78.12-5L80.76-11.40Q81.08-12.24 81.08-12.84L81.08-12.84Q81.08-13.84 80.40-14.40Q79.72-14.96 78.52-14.96L78.52-14.96Q78.44-14.96 78.44-15.20Q78.44-15.44 78.52-15.44L78.52-15.44Q79.60-15.44 80.16-15.40L80.16-15.40L82.56-15.36L84.16-15.40Q84.64-15.44 85.64-15.44L85.64-15.44Z M102.52-2.60L102.60-2.64Q102.68-2.64 102.78-2.48Q102.88-2.32 102.80-2.24L102.80-2.24Q101.32-0.80 99.80-0.16Q98.28 0.48 96.48 0.48L96.48 0.48Q93.96 0.48 92.12-0.58Q90.28-1.64 89.32-3.42Q88.36-5.20 88.36-7.28L88.36-7.28Q88.36-9.60 89.52-11.56Q90.68-13.52 92.74-14.66Q94.80-15.80 97.40-15.80L97.40-15.80Q99.88-15.80 101.24-14.68Q102.60-13.56 102.60-11.20L102.60-11.20Q102.60-9.96 102.16-9.96L102.16-9.96L92.44-9.92Q92.40-9.64 92.40-9L92.40-9Q92.40-5.48 94.02-3.48Q95.64-1.48 98.68-1.48L98.68-1.48Q99.76-1.48 100.52-1.72Q101.28-1.96 102.52-2.60L102.52-2.60ZM95.88-15Q94.56-15 93.68-13.86Q92.80-12.72 92.52-10.72L92.52-10.72L98.32-10.80Q98.28-12.84 97.72-13.92Q97.16-15 95.88-15L95.88-15Z"></path></g>
                </svg>
            </g>
            <g opacity="1" transform="rotate(0 185.7355 143.90090000000004)">
                <svg width="41.4884" height="76.6973" x="185.7355" y="143.90090000000004" version="1.1" preserveAspectRatio="none" viewBox="-229.7999725341797 351.0999755859375 49.60392761230469 91.70004272460938">
                <g transform="matrix(1 0 0 1 0 0)" class="aQjBTis6fwcolors-0"><switch><g><path d="M-204.7,374.9C-204.7,374.9-204.7,374.9-204.7,374.9c0,5.1-3.1,9.5-7.4,11.4c0,0,0,0,0,0c-0.1,0-0.2,0.1-0.2,0.1    c0,0,0,0,0,0c-1.8,0.8-1.7,2.2-1.7,2.2l0,0l0,0l1.3,50.1c0.1,2.3-1.8,4.1-4,4.1h-1c-2.3,0-4.1-1.9-4-4.1l1.3-50.2    c0-0.3-0.1-1.4-1.7-2.1c-4.5-1.9-7.7-6.4-7.7-11.6h0l0.9-21.6c0-1.4,1.1-2,1.6-2v23.7h0v-23.7c0.6,0,1.6,0.7,1.6,2l0.9,21.6h5.1    l0.9-21.6c0-1.4,1.1-2,1.6-2v23.7h0v-23.7c0.6,0,1.6,0.7,1.6,2l0.9,21.6h5.1l0.9-21.6c0-1.4,1.1-2,1.6-2v23.7h0v-23.7    c0.6,0,1.6,0.7,1.6,2L-204.7,374.9z M-181.4,386.8L-181.4,386.8l-0.1-3.6v-23.5c0-2.4-0.8-8.5-3.6-8.6c0,0,0,0,0,0    c-5.1,0-9.3,11.1-9.3,24.9c0,9.1,3.5,19.6,6.2,24.1l-1,37.8c-0.1,2.3,1.8,4.1,4,4.1h1c2.3,0,4.1-1.9,4-4.1L-181.4,386.8z"></path></g></switch></g>
                </svg>
            </g>
            <g opacity="1" transform="rotate(0 0 40.75290000000001)">
                <svg width="65.7699" height="19.8625" x="0" y="40.75290000000001" version="1.1" preserveAspectRatio="none" viewBox="9.3149995803833 38.935997009277344 80 24.160003662109375">
                <g transform="matrix(1 0 0 1 0 0)" class="aBuJNUX_TZcolors-0"><g><path d="M33.071,54.396c0-1.31-4.107-3.381-6.702-3.381c2.595,0,6.702-2.072,6.702-3.382   c0,1.31,4.11,3.382,6.704,3.382C37.181,51.016,33.071,53.087,33.071,54.396z"></path><g><path d="M9.315,51.015c4.676,0,12.081-7.403,12.081-12.079c0,4.676,7.405,12.079,12.081,12.079    c-4.676,0-12.081,7.405-12.081,12.081C21.396,58.42,13.991,51.015,9.315,51.015z"></path><g><line x1="89.315" y1="51.018" x2="31.139" y2="51.018"></line><path d="M89.315,51.107c-9.695,0.262-19.393,0.475-29.09,0.636c-4.848,0.097-9.695,0.299-14.542,0.181     c-4.848-0.165-9.697-0.296-14.544-0.816v-0.181c4.848-0.521,9.697-0.651,14.544-0.815c4.848-0.119,9.695,0.083,14.542,0.181     c9.697,0.161,19.395,0.373,29.09,0.635V51.107z"></path></g></g></g></g>
                </svg>
            </g>
            <g opacity="1" transform="rotate(0 339 40.75290000000001)">
                <svg width="65.7699" height="19.8625" x="339" y="40.75290000000001" version="1.1" preserveAspectRatio="none" viewBox="9.3149995803833 38.935997009277344 80 24.160003662109375">
                <g transform="matrix(-1 0 0 -1 98.6299991607666 102.03199768066406)" class="aepP6SCxH2colors-0"><g><path d="M33.071,54.396c0-1.31-4.107-3.381-6.702-3.381c2.595,0,6.702-2.072,6.702-3.382   c0,1.31,4.11,3.382,6.704,3.382C37.181,51.016,33.071,53.087,33.071,54.396z"></path><g><path d="M9.315,51.015c4.676,0,12.081-7.403,12.081-12.079c0,4.676,7.405,12.079,12.081,12.079    c-4.676,0-12.081,7.405-12.081,12.081C21.396,58.42,13.991,51.015,9.315,51.015z"></path><g><line x1="89.315" y1="51.018" x2="31.139" y2="51.018"></line><path d="M89.315,51.107c-9.695,0.262-19.393,0.475-29.09,0.636c-4.848,0.097-9.695,0.299-14.542,0.181     c-4.848-0.165-9.697-0.296-14.544-0.816v-0.181c4.848-0.521,9.697-0.651,14.544-0.815c4.848-0.119,9.695,0.083,14.542,0.181     c9.697,0.161,19.395,0.373,29.09,0.635V51.107z"></path></g></g></g></g>
                </svg>
            </g>
        </svg>
```

**Screenshots**
```
 TypeError: Cannot read properties of undefined (reading '0')
     at reflectPoint$1 (/Users/user/Projects/svgop/src/tmp/svgo.js:43635:38)
     at /Users/user/Projects/svgop/src/tmp/svgo.js:43277:44
     at Array.filter (<anonymous>)
     at filters$1 (/Users/user/Projects/svgop/src/tmp/svgo.js:42872:16)
     at Object.enter (/Users/user/Projects/svgop/src/tmp/svgo.js:42658:21)
     at visit (/Users/user/Projects/svgop/node_modules/svgo/lib/xast.js:52:30)
     at visit (/Users/user/Projects/svgop/node_modules/svgo/lib/xast.js:68:9)
     at visit (/Users/user/Projects/svgop/node_modules/svgo/lib/xast.js:68:9)
     at visit (/Users/user/Projects/svgop/node_modules/svgo/lib/xast.js:68:9)
     at visit (/Users/user/Projects/svgop/node_modules/svgo/lib/xast.js:68:9)
```

**Desktop (please complete the following information):**

- SVGO Version 3.3.2
- NodeJs Version 20
- OS: MacOS

**Additional context**

Looks like it was similar issue https://github.com/svg/svgo/issues/1926

**Comment by mikeKlech** [comment]
have same error
