### ISSUE TITLE
Crash on undefined controlPoint with specific precision setting

### ISSUE THREAD

**Issue by virtulis** [svg/svgo#2077]
**Describe the bug**
This specific SVG causes a crash to happen specifically when `floatPrecision: 2` is set. Only this SVG, only this value.
Might be related to the note in #1927 and seems to be a rather rare occurrence indeed.

```
SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/plugins/convertPathData.js:1160
  return [2 * base[0] - controlPoint[0], 2 * base[1] - controlPoint[1]];
                                    ^

TypeError: Cannot read properties of undefined (reading '0')
    at reflectPoint (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/plugins/convertPathData.js:1160:37)
    at SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/plugins/convertPathData.js:802:43
    at Array.filter (<anonymous>)
    at filters (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/plugins/convertPathData.js:397:15)
    at Object.enter (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/plugins/convertPathData.js:183:20)
    at visit (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/lib/xast.js:52:30)
    at visit (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/lib/xast.js:68:9)
    at visit (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/lib/xast.js:61:7)
    at invokePlugins (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/lib/svgo/plugins.js:25:7)
    at Object.fn (SNIP/svgo/node_modules/.pnpm/svgo@3.3.2/node_modules/svgo/lib/svgo/plugins.js:57:7)
```
![crash](https://github.com/user-attachments/assets/8aa1b3a3-e9ad-4bca-a60a-6932bfc11f41)

**To Reproduce**

```bash
svgo crash.svg -o test.svg --precision 2
```

or

```js
const orig = await readFile("crash.svg", "utf-8");
const opt = optimize(orig, {
  floatPrecision: 2,
});
```

**Expected behavior**
SVG is optimized.

**Desktop (please complete the following information):**

- SVGO Version 3.3.2
- NodeJs Version 22.9.0
- OS: Linux (multiple)

**Additional context**
The SVG itself is output of `pdf2svg` on a PDF, I believe.

**Comment by virtulis** [comment]
Sorry I read the comments and saw this was reverted. Not sure if I should close this one or reopen the original report.
