### ISSUE TITLE
config.js fails to properly parse .svgo.yml

### ISSUE THREAD

**Issue by brykov** [svg/svgo#223]
All of a sudden I started getting the following error from the svgo:

```
/somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/config.js:56
    return plugins.map(function(item) {
                   ^
TypeError: Cannot call method 'map' of undefined
    at preparePluginsArray (/somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/config.js:56:20)
    at module.exports (/somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/config.js:31:28)
    at new module.exports (/somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:20:19)
    at /somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/index.js:21:20
    at next (/somepath/gulp-imagemin/node_modules/imagemin/node_modules/ware/lib/index.js:56:8)
    at /somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/index.js:22:20
    at next (/somepath/gulp-imagemin/node_modules/imagemin/node_modules/ware/lib/index.js:56:8)
    at /somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/index.js:22:20
    at next (/somepath/gulp-imagemin/node_modules/imagemin/node_modules/ware/lib/index.js:56:8)
    at /somepath/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/index.js:19:20
```

I've done a simple research and found out that the credit goes to line 29 of lib/svgo/config.js:

```
defaults = EXTEND({}, require('../../.svgo.yml'));
```

For some reason ```require('../../.svgo.yml')``` returns an array with one element with index "0" instead of returning the YML file directly. So the quick fix would be like this:

```
defaults = EXTEND({}, require('../../.svgo.yml')[0]);
```

But I am not sure I'm getting all this right. Maybe it is my environment to blame or something. Please advise.

**Comment by GreLI** [comment]
Should be fixed by a2f77efa531e174af8ce86903831e51ec8661808.
