### ISSUE TITLE
error with <foreignObject> inside SVG

### ISSUE THREAD

**Issue by Eduruiz** [svg/svgo#279]
I'm trying to compile some svg with a `<foreignObject>` tag and it trows an error when compiling. I'm using gulp plugin imagemin, and I'm not sure if is an svgo or a imagemin issue.

the svg:
`<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
	 width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path d="M24,2.2v19.6c0,1.2-1,2.2-2.2,2.2H16V14h3.5l0.5-3h-4V8.7C16,7.8,16.8,7,17.7,7H19V4h-3c-3,0-4,1.5-4,4v3H9v3h3v10H2.2
	C1,24,0,23,0,21.8V2.2C0,1,1,0,2.2,0h19.6C23,0,24,1,24,2.2z"/>
	<foreignObject>
         <div class='test'>fallback test</div>
     </foreignObject>
</svg>`

and the error log:

[18:09:28] Starting 'images'...
Possibly unhandled TypeError: Cannot read property 'content' of undefined
    at Object.exports.fn (C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\plugins\removeUnknownsAndDefaults.js:83:24)
    at C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\lib\svgo\plugins.js:61:45
    at Array.filter (native)
    at monkeys (C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\lib\svgo\plugins.js:70:17
    at Array.filter (native)
    at monkeys (C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\lib\svgo\plugins.js:70:17
    at Array.filter (native)
    at monkeys (C:\xampp\htdocs\crea\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-svgo\node_modules\svgo\lib\svgo\plugins.js:46:39)

thanks for any help!

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
