### ISSUE TITLE
Possibly unhandled TypeError: Cannot read property 'coords' of undefined

### ISSUE THREAD

**Issue by subtik** [svg/svgo#289]
When I try to run `gulp` in a cloned folder of [google/web-starter-kit](https://github.com/google/web-starter-kit) it prompt me with:
```
Possibly unhandled TypeError: Cannot read property 'coords' of undefined
    at /Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/plugins/convertPathData.js:245:35
    at Array.forEach (native)
    at convertToRelative (/Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/plugins/convertPathData.js:97:10)
    at Object.exports.fn (/Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/plugins/convertPathData.js:58:13)
    at /Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:61:45
    at Array.filter (native)
    at monkeys (/Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at /Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:70:17
    at Array.filter (native)
    at monkeys (/Users/subtik/Sites/grttd/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:46:39)
```

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
