### ISSUE TITLE
TypeError: Cannot read property '0' of undefined -- svg2js.js

### ISSUE THREAD

**Issue by kaldrenon** [svg/svgo#332]
I have been using `svgo` through [imagemin](https://github.com/imagemin/imagemin) and [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin) for the past several weeks.

This morning, I found that my build process is failing, and based on the stack trace, it looks like svgo is the root cause.

    TypeError: Cannot read property '0' of undefined
      at trim (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:152:59)
      at Object.sax.onclosetag (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:125:13)
      at emit (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:615:33)
      at emitNode (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:620:3)
      at closeTag (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:861:5)
      at Object.write (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:1294:29)
      at module.exports (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:144:9)
      at SVGO._optimizeOnce (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:56:5)
      at SVGO.optimize (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:48:11)
      at Through2._transform (./node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/index.js:32:9)
      at Through2.Transform._read (./node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)

If I can provide additional information to help you diagnose the issue, please let me know what to provide.

**Comment by GreLI** [comment]
It would be nice if you provide a sample image. Is there an empty ``<text></text>``?

**Comment by bastnic** [comment]
Same as #336, whicheas has a test case.

**Comment by GreLI** [comment]
#336 is definitely different case which was fixed in ae2981cdea6696124587e9c39906ea90312aaf83

**Comment by GreLI** [comment]
Please, check if this fixes your issue.
