### ISSUE TITLE
<text> with only whitespace in content throw exception

### ISSUE THREAD

**Issue by LoicMahieu** [svg/svgo#359]
##### Throw error
```
echo '
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300">
<g>
  <text x="20" y="40">Hello</text>
  <text> </text>
</g>
</svg>
' | svgo -i - -o -
[TypeError: Cannot read property 'length' of undefined]
```
##### Does not throw error
(remark no whitespaces)
```
echo '
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300">
<g>
  <text x="20" y="40">Hello</text>
  <text></text>
</g>
</svg>
' | svgo -i - -o -
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300"><text x="20" y="40">Hello</text></svg>
```

Both documents are considered valid by validators.
Tested on v0.5.1

**Comment by GreLI** [comment]
Yeah, it's been fixed after v0.5.1

**Comment by LoicMahieu** [comment]
In fact this does not throw an exception on v0.5.1 cause to CLI seems ignore errors.
```js

var svgGood = [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300">',
  '<g>',
  '  <text x="20" y="40">Hello</text>',
  '  <text></text>',
  '</g>',
  '</svg>'
].join('\n');

var svgWrong = [
  '<?xml version="1.0" encoding="utf-8"?>',
  '<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300">',
  '<g>',
  '  <text x="20" y="40">Hello</text>',
  '  <text> </text>',
  '</g>',
  '</svg>'
].join('\n');

var SVGO = require('svgo');
var fs = require('fs');
var path = require('path');
var findup = require('findup');

// Get version
console.log(
  'SVGO version:',
  JSON.parse(
    fs.readFileSync(
      path.join(
        findup.sync(require.resolve('svgo'), 'package.json'),
        'package.json'
      )
    )
  ).version
);

// Run
var svgo = new SVGO();

svgo.optimize(svgGood, function (res) {
  if (res.error) {
    console.log('Never called !', res.error);
  }

  console.log('svgGood is good! Result:');
  console.log(res.data);
});

svgo.optimize(svgWrong, function (res) {
  console.log('Never called but throws an exception!');
});

```

Output:
```
SVGO version: 0.5.1
svgGood is good! Result:
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300"><text x="20" y="40">Hello</text></svg>
/private/tmp/test-svgo/node_modules/svgo/lib/svgo/svg2js.js:155
        while (end && !end.text) end = end.content[end.content.length - 1];
                                                              ^
TypeError: Cannot read property 'length' of undefined
    at trim (/private/tmp/test-svgo/node_modules/svgo/lib/svgo/svg2js.js:155:63)
    at Object.sax.onclosetag (/private/tmp/test-svgo/node_modules/svgo/lib/svgo/svg2js.js:125:13)
    at emit (/private/tmp/test-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/private/tmp/test-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/private/tmp/test-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/private/tmp/test-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:1294:29)
    at module.exports (/private/tmp/test-svgo/node_modules/svgo/lib/svgo/svg2js.js:144:9)
    at SVGO._optimizeOnce (/private/tmp/test-svgo/node_modules/svgo/lib/svgo.js:56:5)
    at SVGO.optimize (/private/tmp/test-svgo/node_modules/svgo/lib/svgo.js:48:11)
    at Object.<anonymous> (/private/tmp/test-svgo/test.js:52:6)
```

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
