### ISSUE TITLE
[BROKEN] v0.7.2 doesn't publish .svgo.yml which breaks vue-loader

### ISSUE THREAD

**Issue by e-cloud** [svg/svgo#676]
```
ERROR in ./~/css-loader?{"minimize":true,"sourceMap":true}!./~/vue-loader/lib/style-rewriter.js?{"id":"data-v-6b08869a","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: Error: ENOENT: no such file or directory, open '/home/my-project/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:582:18)
    at Object.fs.readFileSync (fs.js:489:33)
    at module.exports (/home/my-project/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/home/my-project/node_modules/svgo/lib/svgo.js:21:19)
    at /home/my-project/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/home/my-project/node_modules/postcss/lib/postcss.js:150:35)
    at /home/my-project/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (native)
    at /home/my-project/node_modules/cssnano/dist/index.js:282:29
    at creator (/home/my-project/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/home/my-project/node_modules/css-loader/lib/processCss.js:187:16)
    at Object.module.exports (/home/my-project/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?{"minimize":true,"sourceMap":true}!./~/vue-loader/lib/style-rewriter.js?{"id":"data-v-6b08869a","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-358
 @ ./src/App.vue
 @ ./src/main.js
```

I've checked v0.7.1, it has `.svgo.yml` at the root dir.

**Comment by e-cloud** [comment]
sorry, I find out it's broken by yarn's clean command.
