### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by proov** [svg/svgo#810]
I have this error on an clean SVG Sprite `icons.svg` (generated by fontastic.me) which contains this :

``` html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  
  <symbol id="icon-best-prices" viewBox="0 0 512 512">
    <path d="m509 494l-120-120c37-39 59-92 59-150 0-124-100-224-224-224-124 0-224 100-224 224 0 124 100 224 224 224 58 0 111-22 150-59l120 120c2 2 5 3 7 3 4 0 6-1 8-3 4-4 4-11 0-15z m-285-67c-112 0-203-91-203-203 0-112 91-203 203-203 112 0 203 91 203 203 0 112-91 203-203 203z m21-299c12 0 24 2 36 5l3-25c-15-3-28-6-39-6-26 0-47 8-62 24-14 15-23 37-24 65l-29 0 0 20 29 0 0 23-29 0 0 20 29 0c1 29 8 51 23 67 15 16 37 24 63 24 13 0 26-3 39-6l-3-25c-11 3-23 5-36 5-18 0-32-5-41-17-10-12-15-28-15-48l62 0 0-20-62 0 0-23 62 0 0-19-62 0c1-20 5-36 15-47 10-12 24-17 41-17z"/>
  </symbol>

  <symbol id="icon-direction-right" viewBox="0 0 512 512">
    <path d="m0 255c0 6 2 11 6 16 4 4 9 5 15 5l418 0-91 93c-11 9-11 19-1 30 11 10 21 10 30-1l128-128c3-2 4-5 5-7 1-3 2-5 2-8 0-2-1-5-2-8-1-2-2-5-5-6l-128-128c-9-11-19-11-30-1-10 10-10 20 1 30l91 92-418 0c-6 0-11 2-15 6-4 3-6 8-6 15z"/>
  </symbol>

  <!-- More symbols here -->
  
</svg>
``` 

I'm using `gulp-imagemin` with the lastest version of svgo `0.7.2`, do you have an idea about this ?

More details about the error:
``` node
events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'filter' of undefined
    at monkeys (/Users/sylvainprevost/Sites/assurange/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at perItem (/Users/sylvainprevost/Sites/assurange/node_modules/svgo/lib/svgo/plugins.js:77:12)
    at /Users/sylvainprevost/Sites/assurange/node_modules/svgo/lib/svgo/plugins.js:18:24
    at Array.forEach (<anonymous>)
    at module.exports (/Users/sylvainprevost/Sites/assurange/node_modules/svgo/lib/svgo/plugins.js:14:13)
    at /Users/sylvainprevost/Sites/assurange/node_modules/svgo/lib/svgo.js:63:17
    at SAXParser.sax.onend (/Users/sylvainprevost/Sites/assurange/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/Users/sylvainprevost/Sites/assurange/node_modules/sax/lib/sax.js:624:35)
    at end (/Users/sylvainprevost/Sites/assurange/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.write (/Users/sylvainprevost/Sites/assurange/node_modules/sax/lib/sax.js:975:14)
```

**Comment by GreLI** [comment]
As far as I see SVGO by default just optimizes it to 0 bytes due to `display: none` and non-rendered symbols. But the error appears only with `--multipass` option. I'd recommend to disable `removeHiddenElems` and `removeUselessDefs` plugins.

**Comment by GreLI** [comment]
SVGO v1.0.0 with this change has been released now.
