### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jaswrks** [svg/svgo#846]
Running SVGO 1.0.3 and I'm seeing a consistent repeatable failure
when trying to optimize [this SVG file](https://gist.github.com/jaswrks/7a3092e61d232aa8e219f4e68b9deea3).

Here is the error output from the command line.
I used `$ svgo --precision=4 --output=[file] [input file]` with only default options.

```
 'TypeError: Cannot read property '0' of undefined'
at multiplyTransformMatrices (/usr/lib/node_modules/svgo/plugins/_transforms.js:306:17)'
at /usr/lib/node_modules/svgo/plugins/_transforms.js:69:20'
at Array.reduce (<anonymous>)'
at exports.transformsMultiply (/usr/lib/node_modules/svgo/plugins/_transforms.js:68:26)'
at exports.applyTransforms (/usr/lib/node_modules/svgo/plugins/_path.js:182:18)'
at Object.exports.fn (/usr/lib/node_modules/svgo/plugins/convertPathData.js:76:24)'
at /usr/lib/node_modules/svgo/lib/svgo/plugins.js:61:45'
at Array.filter (<anonymous>)'
at monkeys (/usr/lib/node_modules/svgo/lib/svgo/plugins.js:48:39)'
at /usr/lib/node_modules/svgo/lib/svgo/plugins.js:68:17'
```

Referencing: https://gist.github.com/jaswrks/7a3092e61d232aa8e219f4e68b9deea3

**Comment by GreLI** [comment]
Incorrect image:
```xml
<g fill="#ddd" style="opacity:0.14133333333333;"
transform="translate(169.74, 169.74) rotate(45, 33.948, 33.948">
```
(line break added for readability)
notice the absent `)` after the last `rotate`. It breaks parser and data structure.
