### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by wifivepl** [svg/svgo#914]
Hey! I am having trouble running the SVGO through console. Each time I send ANY command I get the following syntax error:

/opt/plesk/node/8/lib/node_modules/svgo/lib/svgo/coa.js:18
    noop = () => {},
            ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/plesk/node/8/lib/node_modules/svgo/bin/svgo:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I tried it on node.js v8.9.3, v7.4.0, v6.12.2

**Comment by GreLI** [comment]
Very strange error. Cannot reproduce in v8.9.4 (and one some older v6 ones). Seems like some Node.js error. Are you sure you have correct Node.js version? Have you some unstable flags on?

**Comment by wifivepl** [comment]
I reinstalled nodejs and everything works fine! Dunno why SVGO was the only app having problem with that, but I'm glad it's fine now. Thank you!

**Comment by travisdowns** [comment]
I had this error too when my nodejs version was too old 4.2.x something which comes default with Ubuntu 16.04. Using a newer version of node helped.
